[package]
name = "salaryman"
version = "0.0.1"
edition = "2024"
authors = ["Ren Kararou <ren@kararou.space>"]
description = "A very simple service management framework"
readme = "README.md"
license = "MIT"
homepage = "https://sr.ht/~spicywolf/salaryman"
repository = "https://svn.lesbianunix.dev/viewvc/salaryman/trunk/"
categories = ["command-line-utilities"]
keywords = ["service-management", "unix"]
publish = ["crate-io"]

[features]
#default = []
default = ["protocol", "smd", "sm-cli"]
protocol = [
	"dep:bincode",
]
smd = [
	"dep:clap",
	"dep:rayon",
	"dep:toml",
	"protocol",
]
sm-cli = [
	"dep:clap",
	"dep:toml",
	"protocol",
]

[dependencies]
bincode = { version = "2.0.1", features = ["serde"], optional = true }
clap = { version = "4.5.39", features = ["derive"], optional = true }
rayon = { version = "1.10.0", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
toml = { version = "0.8.22", optional = true }
uuid = { version = "1.17.0", features = ["v4", "serde"] }

[[bin]]
name = "smd"
path = "src/server/main.rs"
test = false
bench = false
required-features = ["smd"]

[[bin]]
name = "sm"
path = "src/cli/main.rs"
test = false
bench = false
required-features = ["sm-cli"]

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

