socket = "/tmp/salaryman.sock"

[[service]]
uuid = "4a8807b8-32ef-4cde-b9ed-8eabfd6cdb15"
name = "minecraft"
command = "java"
args = "-jar /minecraft/server.jar nogui"
directory = "/minecraft/data"
autostart = true

